import type { ThreatEntry } from '../types';

export const THREATS: ThreatEntry[] = [
  {
    id: 'phishing',
    name: 'Phishing',
    category: 'Social Engineering',
    risk_level: 'high',
    description: 'Deceptive messages impersonating trusted entities to steal credentials or personal information.',
    indicators: ['Urgent language', 'Spoofed sender address', 'Suspicious links', 'Request for credentials', 'Generic greetings'],
    examples: ['"Your account will be suspended — verify now"', '"Unusual sign-in activity detected"', '"You have won a prize — claim here"'],
  },
  {
    id: 'malware-link',
    name: 'Malware Links',
    category: 'Malicious Content',
    risk_level: 'critical',
    description: 'URLs or QR codes that deliver malware payloads when visited, including ransomware, spyware, and trojans.',
    indicators: ['Shortened URLs', 'Mismatched domains', 'Drive-by download prompts', 'Executable file links'],
    examples: ['bit.ly redirects to .exe downloads', 'Fake invoice PDFs with embedded macros'],
  },
  {
    id: 'credential-harvesting',
    name: 'Credential Harvesting',
    category: 'Data Theft',
    risk_level: 'critical',
    description: 'Fake login pages or forms designed to capture usernames, passwords, and MFA codes.',
    indicators: ['Clone login pages', 'HTTP (not HTTPS)', 'Mismatched domain', 'Password field on unexpected page'],
    examples: ['Fake Microsoft 365 login page', 'Impersonated bank portal', 'Fake VPN login portal'],
  },
  {
    id: 'business-email-compromise',
    name: 'Business Email Compromise',
    category: 'Fraud',
    risk_level: 'high',
    description: 'Impersonation of executives or suppliers to authorize fraudulent transfers or data disclosures.',
    indicators: ['CEO/CFO impersonation', 'Wire transfer requests', 'Urgency + secrecy', 'New payment account details'],
    examples: ['"CFO: urgent wire needed by EOD"', '"Vendor changed bank account — update records"'],
  },
  {
    id: 'smishing',
    name: 'Smishing (SMS Phishing)',
    category: 'Social Engineering',
    risk_level: 'high',
    description: 'Phishing delivered via SMS, often impersonating delivery companies, banks, or government agencies.',
    indicators: ['Unknown sender', 'Short URLs', 'Requests for personal info', 'Prize/package notifications'],
    examples: ['"Your parcel is held — confirm details"', '"HMRC tax refund available — claim now"'],
  },
  {
    id: 'qr-phishing',
    name: 'QR Code Phishing (Quishing)',
    category: 'Social Engineering',
    risk_level: 'medium',
    description: 'Malicious QR codes embedded in documents or emails that redirect to phishing sites.',
    indicators: ['QR codes in unexpected contexts', 'Overlaid QR stickers in public', 'QR in email body'],
    examples: ['Parking meter QR stickers', '"Scan to verify your identity" email QR'],
  },
  {
    id: 'data-exfiltration',
    name: 'Data Exfiltration Indicators',
    category: 'Insider / APT',
    risk_level: 'critical',
    description: 'Signals suggesting sensitive data is being prepared for or actively transferred out of the organization.',
    indicators: ['Large file compression', 'Unusual cloud upload activity', 'Access to non-role data', 'Off-hours activity'],
    examples: ['Employee zipping /hr/ folder at 2 AM', 'Mass forwarding emails to personal account'],
  },
  {
    id: 'safe-content',
    name: 'Safe / Benign Content',
    category: 'No Threat',
    risk_level: 'safe',
    description: 'Content that shows no indicators of malicious intent. Regular business communications, internal memos, or public information.',
    indicators: ['Legitimate sender domain', 'No credential requests', 'Expected context', 'No suspicious links'],
    examples: ['Team meeting invite from known colleague', 'Newsletter from a subscribed service'],
  },
];
